repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings. 

  # A short description of the repository that will show up on GitHub
  description: description and branch protection is managed by ./.github/settings.yml with settings inherited from https://raw.githubusercontent.com/dadstaxi/.github/main/.github/settings.yml

branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      restrictions: null
      required_status_checks: null
      enforce_admins: null
      required_pull_request_reviews:
        dismissal_restrictions": {}
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        # The number of approvals required. (1-6)
        required_approving_review_count: 2
      
